# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'celo-sdk-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for celo-sdk-ios

  target 'celo-sdk-iosTests' do
    # Pods for testing
  end

end
